// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shisanshui.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Xproto {

  /// <summary>Holder for reflection information generated from shisanshui.proto</summary>
  public static partial class ShisanshuiReflection {

    #region Descriptor
    /// <summary>File descriptor for shisanshui.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShisanshuiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBzaGlzYW5zaHVpLnByb3RvEgZ4cHJvdG8qzwEKC1NwZWNpYWxUeXBlEhAK",
            "DFNwZWNpYWxfTm9uZRAAEhIKDlRocmVlX1N0cmFpZ2h0EAESDwoLVGhyZWVf",
            "Rmx1c2gQAhIVChFTaXhQYWlyc19IaWdoQ2FyZBADEhoKFkZpdmVQYWlyc19U",
            "aHJlZU9mQUtpbmQQBBINCglPbmVfQmxhY2sQBRILCgdPbmVfUmVkEAYSEQoN",
            "UHVyZV9PbmVfU3VpdBAHEhAKDEFsbF9TdHJhaWdodBAIEhUKEUFsbF9TdHJh",
            "aWdodEZsdXNoEAkqoQEKDENhcmRIYW5kVHlwZRIRCg1DYXJkSGFuZF9Ob25l",
            "EAASDAoISGlnaENhcmQQARILCgdPbmVQYWlyEAISDAoIVHdvUGFpcnMQAxIQ",
            "CgxUaHJlZU9mQUtpbmQQBBIMCghTdHJhaWdodBAFEgkKBUZsdXNoEAYSDQoJ",
            "RnVsbEhvdXNlEAcSCAoERm91chAIEhEKDVN0cmFpZ2h0Rmx1c2gQCSpeCgxI",
            "YW5kT3ZlclR5cGUSGQoVZW51bUhhbmRPdmVyVHlwZV9Ob25lEAASGAoUZW51",
            "bUhhbmRPdmVyVHlwZV9XaW4QARIZChVlbnVtSGFuZE92ZXJUeXBlX0xvc3MQ",
            "AipBCgpBY3Rpb25UeXBlEhcKE2VudW1BY3Rpb25UeXBlX05vbmUQABIaChZl",
            "bnVtQWN0aW9uVHlwZV9ESVNDQVJEEAFCCloILjt4cHJvdG8="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Xproto.SpecialType), typeof(global::Xproto.CardHandType), typeof(global::Xproto.HandOverType), typeof(global::Xproto.ActionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 特殊牌型
  /// </summary>
  public enum SpecialType {
    /// <summary>
    /// 无效牌型
    /// </summary>
    [pbr::OriginalName("Special_None")] SpecialNone = 0,
    /// <summary>
    /// 三顺子 每一墩都是顺子（如  23456、45678、789）
    /// </summary>
    [pbr::OriginalName("Three_Straight")] ThreeStraight = 1,
    /// <summary>
    /// 三同花 每一墩花色相同（如 第一墩都是梅花 第二墩都是方块）
    /// </summary>
    [pbr::OriginalName("Three_Flush")] ThreeFlush = 2,
    /// <summary>
    /// 六对半
    /// </summary>
    [pbr::OriginalName("SixPairs_HighCard")] SixPairsHighCard = 3,
    /// <summary>
    /// 五对 加 三条
    /// </summary>
    [pbr::OriginalName("FivePairs_ThreeOfAKind")] FivePairsThreeOfAkind = 4,
    /// <summary>
    /// 一点黑
    /// </summary>
    [pbr::OriginalName("One_Black")] OneBlack = 5,
    /// <summary>
    /// 一点红
    /// </summary>
    [pbr::OriginalName("One_Red")] OneRed = 6,
    /// <summary>
    /// 清一色 (全黑或全红 可以方块红桃混合)
    /// </summary>
    [pbr::OriginalName("Pure_One_Suit")] PureOneSuit = 7,
    /// <summary>
    /// 一条龙
    /// </summary>
    [pbr::OriginalName("All_Straight")] AllStraight = 8,
    /// <summary>
    /// 至尊清龙
    /// </summary>
    [pbr::OriginalName("All_StraightFlush")] AllStraightFlush = 9,
  }

  /// <summary>
  /// 牌组类型
  /// </summary>
  public enum CardHandType {
    /// <summary>
    /// 无效牌型
    /// </summary>
    [pbr::OriginalName("CardHand_None")] CardHandNone = 0,
    /// <summary>
    /// 单张
    /// </summary>
    [pbr::OriginalName("HighCard")] HighCard = 1,
    /// <summary>
    /// 对牌
    /// </summary>
    [pbr::OriginalName("OnePair")] OnePair = 2,
    /// <summary>
    /// 两对牌：数值相同的两张牌
    /// </summary>
    [pbr::OriginalName("TwoPairs")] TwoPairs = 3,
    /// <summary>
    /// 三条 Three of a kind
    /// </summary>
    [pbr::OriginalName("ThreeOfAKind")] ThreeOfAkind = 4,
    /// <summary>
    /// 顺子(蛇)	Straight
    /// </summary>
    [pbr::OriginalName("Straight")] Straight = 5,
    /// <summary>
    /// 同花(花)	Flush
    /// </summary>
    [pbr::OriginalName("Flush")] Flush = 6,
    /// <summary>
    /// 葫芦
    /// </summary>
    [pbr::OriginalName("FullHouse")] FullHouse = 7,
    /// <summary>
    /// 四条 Four of a Kind：四张同点牌 + 一张
    /// </summary>
    [pbr::OriginalName("Four")] Four = 8,
    /// <summary>
    /// 同花顺	Straight Flush 五张或更多的连续单牌（如： 45678 或 78910JQK ）
    /// </summary>
    [pbr::OriginalName("StraightFlush")] StraightFlush = 9,
  }

  /// <summary>
  /// 一手牌局结束
  /// 可能的结果是：流局、有人赢牌
  /// </summary>
  public enum HandOverType {
    /// <summary>
    /// 没有胡牌，或者流局
    /// </summary>
    [pbr::OriginalName("enumHandOverType_None")] EnumHandOverTypeNone = 0,
    /// <summary>
    /// 赢牌
    /// </summary>
    [pbr::OriginalName("enumHandOverType_Win")] EnumHandOverTypeWin = 1,
    /// <summary>
    /// 输牌
    /// </summary>
    [pbr::OriginalName("enumHandOverType_Loss")] EnumHandOverTypeLoss = 2,
  }

  /// <summary>
  /// 动作类型
  /// 注意为了能够用一个int合并多个动作
  /// 因此所有动作的值均为二进制bit field独立
  /// </summary>
  public enum ActionType {
    /// <summary>
    /// 无效动作
    /// </summary>
    [pbr::OriginalName("enumActionType_None")] EnumActionTypeNone = 0,
    /// <summary>
    /// 出牌
    /// </summary>
    [pbr::OriginalName("enumActionType_DISCARD")] EnumActionTypeDiscard = 1,
  }

  #endregion

}

#endregion Designer generated code
